-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."Category" AS ENUM('Projects', 'Industry', 'Non-technical');--> statement-breakpoint
CREATE TABLE "experience" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "experience_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"startedAt" text NOT NULL,
	"endedAt" text NOT NULL,
	"description" text NOT NULL,
	"companyName" text NOT NULL,
	"companyIcon" text NOT NULL,
	"position" text NOT NULL,
	"companyLink" text,
	"display" boolean DEFAULT false NOT NULL,
	CONSTRAINT "experience_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "experience" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "articles" (
	"slug" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"description" text,
	"content" text,
	"title" text,
	"category" "Category" DEFAULT 'Projects' NOT NULL,
	"published" boolean DEFAULT true NOT NULL,
	CONSTRAINT "articles_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "articles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "books" (
	"name" text PRIMARY KEY NOT NULL,
	"author" text NOT NULL,
	"description" text,
	"image" text,
	"link" text DEFAULT 'NULL'
);
--> statement-breakpoint
ALTER TABLE "books" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "puzzles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "puzzles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"input" text NOT NULL,
	"description" text NOT NULL,
	"answer" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "puzzles" ENABLE ROW LEVEL SECURITY;
*/